package com.kitakkun.jetwhale.host.data.update

import com.kitakkun.jetwhale.host.model.HostVersionInfo
import io.ktor.client.engine.mock.MockEngine
import io.ktor.client.engine.mock.respond
import io.ktor.client.engine.mock.respondError
import io.ktor.http.HttpStatusCode
import kotlinx.coroutines.runBlocking
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

class UpdateCheckServiceTest {
    private fun serviceRespondingMetadata(metadata: String?, hostVersion: String): UpdateCheckService = UpdateCheckService(
        MockEngine { request ->
            if (request.url.toString().endsWith("/metadata.properties") && metadata != null) {
                respond(metadata)
            } else {
                respondError(HttpStatusCode.NotFound)
            }
        },
        HostVersionInfo(hostVersion),
    )

    @Test
    fun `newer site version is reported as an available update`() = runBlocking {
        val service = serviceRespondingMetadata(
            metadata = """
                # generated by Conveyor
                app.version = 1.0.0.9
            """.trimIndent(),
            hostVersion = "1.0.0-alpha08",
        )
        val result = service.checkForUpdates()
        assertEquals("1.0.0.8", result.currentVersion)
        assertEquals("1.0.0.9", result.latestVersion)
        assertEquals(true, result.updateAvailable)
    }

    @Test
    fun `same site version is reported as up to date`() = runBlocking {
        val service = serviceRespondingMetadata(
            metadata = "app.version=1.0.0.8",
            hostVersion = "1.0.0-alpha08",
        )
        assertEquals(false, service.checkForUpdates().updateAvailable)
    }

    @Test
    fun `unreachable update site throws`(): Unit = runBlocking {
        val service = serviceRespondingMetadata(metadata = null, hostVersion = "1.0.0-alpha08")
        assertFailsWith<UpdateCheckException> { service.checkForUpdates() }
    }

    @Test
    fun `pre-release suffix maps to a numeric fourth segment`() {
        assertEquals("1.0.0.8", UpdateCheckService.numericVersionOf("1.0.0-alpha08"))
        assertEquals("1.0.0", UpdateCheckService.numericVersionOf("1.0.0"))
    }

    @Test
    fun `version comparison handles differing segment counts`() {
        assertEquals(true, UpdateCheckService.isNewer(candidate = "1.0.1", current = "1.0.0.8"))
        assertEquals(false, UpdateCheckService.isNewer(candidate = "1.0.0", current = "1.0.0.8"))
        assertEquals(false, UpdateCheckService.isNewer(candidate = "1.0.0.8", current = "1.0.0.8"))
    }
}
