name: "Setup JDK"
description: "Set up JDK and Gradle caching"

inputs:
  java-version:
    description: "Java version"
    default: "17"

runs:
  using: "composite"
  steps:
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v5.0.0

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v5.2.0
      with:
        distribution: corretto
        java-version: ${{ inputs.java-version }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5.0.0
      with:
        gradle-version: wrapper

    - name: Set konan cache key
      id: konan-cache-key
      shell: bash
      run: echo "KOTLIN_VERSION=$(grep -oE 'kotlin\s*=\s*"[0-9.]*"' gradle/libs.versions.toml | grep -oE '[0-9.]+')" >> $GITHUB_OUTPUT

    - name: Cache Konan
      uses: actions/cache@v5.0.2
      with:
        path: |
          ~/.konan
        key: v1-konan-${{ runner.os }}-${{ hashFiles('.xcode-version') }}-${{ steps.konan-cache-key.outputs.KOTLIN_VERSION }}
