package com.kitakkun.jetwhale.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

/**
 * Generates the `applyJetWhaleBuildEnvironment()` source file that registers the build machine's host
 * candidates with the agent runtime. When injection is disabled (or no address was found), the
 * generated function is a no-op so app code that calls it keeps compiling.
 */
@DisableCachingByDefault(because = "Trivial code generation from build-time host info; caching adds no value")
abstract class GenerateBuildEnvironmentTask : DefaultTask() {
    @get:Input
    abstract val injectEnabled: Property<Boolean>

    @get:Input
    @get:Optional
    abstract val hostName: Property<String>

    @get:Input
    abstract val addresses: ListProperty<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val packageDir = outputDir.get().asFile.resolve(PACKAGE.replace('.', '/'))
        packageDir.mkdirs()
        packageDir.resolve("JetWhaleBuildEnvironmentGenerated.kt").writeText(renderSource())
    }

    private fun renderSource(): String {
        val enabled = injectEnabled.get()
        val addressList = addresses.get()
        val host = hostName.orNull

        val body = if (!enabled || (addressList.isEmpty() && host == null)) {
            // Injection disabled or nothing to inject: emit a no-op so callers still compile/link.
            "    // Build-host candidate injection is disabled or found no addresses."
        } else {
            val addressLiterals = addressList.joinToString(separator = ", ") { "\"${it.escape()}\"" }
            val hostLiteral = host?.let { "\"${it.escape()}\"" } ?: "null"
            """    JetWhaleBuildEnvironment.registerHostCandidates(
            |        hostName = $hostLiteral,
            |        addresses = listOf($addressLiterals),
            |    )
            """.trimMargin()
        }

        return """
            |// Generated by the JetWhale Gradle plugin. Do not edit.
            |package $PACKAGE
            |
            |import com.kitakkun.jetwhale.agent.runtime.JetWhaleBuildEnvironment
            |
            |/**
            | * Registers the build machine's host candidates captured at build time. Call once before
            | * `startJetWhale {}`.
            | */
            |public fun applyJetWhaleBuildEnvironment() {
            |$body
            |}
            |
        """.trimMargin()
    }

    private fun String.escape(): String = replace("\\", "\\\\").replace("\"", "\\\"")

    private companion object {
        const val PACKAGE = "com.kitakkun.jetwhale.generated"
    }
}
