package com.kitakkun.jetwhale.host.data.plugin

import com.github.javakeyring.Keyring
import com.github.javakeyring.PasswordAccessException
import dev.zacsweers.metro.AppScope
import dev.zacsweers.metro.ContributesBinding
import dev.zacsweers.metro.Inject
import dev.zacsweers.metro.SingleIn
import java.security.MessageDigest
import java.security.SecureRandom
import java.util.Base64
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * [TrustRegistrySigner] backed by an HMAC-SHA256 key stored in the OS credential store (macOS
 * Keychain, Windows Credential Manager, or Linux Secret Service via java-keyring). The key is
 * generated on first use and never touches the app data directory, so rewriting files under
 * `~/.jetwhale` alone cannot produce a registry that verifies.
 *
 * When the credential store is unreachable (headless Linux without a Secret Service, etc.) the
 * signer degrades to [TrustRegistrySigner.Verification.UNAVAILABLE] rather than locking the user
 * out of their plugins; the repository decides how to treat that case.
 */
@SingleIn(AppScope::class)
@ContributesBinding(AppScope::class)
@Inject
class KeyringTrustRegistrySigner : TrustRegistrySigner {
    /** True when the key was generated by this process, i.e. no key existed before this run. */
    private var keyCreatedThisRun = false

    private val hmacKey: ByteArray? by lazy {
        try {
            Keyring.create().use { keyring ->
                try {
                    Base64.getDecoder().decode(keyring.getPassword(KEYRING_SERVICE, KEYRING_ACCOUNT))
                } catch (e: PasswordAccessException) {
                    // No key stored yet: first run (or first run since this feature shipped).
                    val newKey = ByteArray(KEY_LENGTH_BYTES).also { SecureRandom().nextBytes(it) }
                    keyring.setPassword(KEYRING_SERVICE, KEYRING_ACCOUNT, Base64.getEncoder().encodeToString(newKey))
                    keyCreatedThisRun = true
                    newKey
                }
            }
        } catch (e: Exception) {
            println("OS credential store unavailable, plugin trust registry will not be signature-checked: ${e.message}")
            null
        }
    }

    override fun sign(payload: String): String? {
        val key = hmacKey ?: return null
        return Base64.getEncoder().encodeToString(hmac(key, payload))
    }

    override fun verify(payload: String, signature: String?): TrustRegistrySigner.Verification {
        val key = hmacKey ?: return TrustRegistrySigner.Verification.UNAVAILABLE
        if (signature == null) {
            // An unsigned registry is legitimate only if it predates the signing key itself
            // (an upgrade from a version without signing). Once a key exists, every persisted
            // registry carries a signature, so a missing one means the file was replaced.
            return if (keyCreatedThisRun) TrustRegistrySigner.Verification.VALID else TrustRegistrySigner.Verification.INVALID
        }
        val expected = hmac(key, payload)
        val actual = try {
            Base64.getDecoder().decode(signature)
        } catch (e: IllegalArgumentException) {
            return TrustRegistrySigner.Verification.INVALID
        }
        return if (MessageDigest.isEqual(expected, actual)) {
            TrustRegistrySigner.Verification.VALID
        } else {
            TrustRegistrySigner.Verification.INVALID
        }
    }

    private fun hmac(key: ByteArray, payload: String): ByteArray {
        val mac = Mac.getInstance(HMAC_ALGORITHM)
        mac.init(SecretKeySpec(key, HMAC_ALGORITHM))
        return mac.doFinal(payload.toByteArray(Charsets.UTF_8))
    }

    companion object {
        private const val KEYRING_SERVICE = "JetWhale"
        private const val KEYRING_ACCOUNT = "plugin-trust-registry-hmac"
        private const val HMAC_ALGORITHM = "HmacSHA256"
        private const val KEY_LENGTH_BYTES = 32
    }
}
