name: Run Test

on:
  push:
    branches:
      - main
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '**/*.java'
      - 'gradle/**'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/test.yml'
      - '.github/actions/setup-java/**'
  pull_request:
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '**/*.java'
      - 'gradle/**'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/test.yml'
      - '.github/actions/setup-java/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java

      - name: Run tests
        run: ./gradlew check
